### ISSUE TITLE
Geshi - SQL not properly recognized

### ISSUE THREAD

**Issue by vic-t** [turnermm/codedoc#3]
`<codedoc code:sql>` does not recognize sql comments (which are prefixed by two dashes, `--`)

**Comment by turnermm** [comment]
Please give an example

**Comment by vic-t** [comment]
```
<codedoc code:sql>
-- 
-- This is an SQL comment
--
ALTER TABLE "Person" RENAME TO People;
</codedoc>
```

**Comment by turnermm** [comment]
```
<codedoc code:sql>
~~codedoc:clean:--~~\\
~~codedoc:clean:--This is an SQL comment--~~\\
~~codedoc:clean:--~~

ALTER TABLE "Person" RENAME TO People;
</codedoc>
```

See: https://www.dokuwiki.org/doku.php?id=plugin:codedoc#literals

**Comment by vic-t** [comment]
I regularly copy paste large pieces of SQL code that include comments all over the place. So this workaround is just not at all practical. I appreciate you answered (in record time, by the way) but if that's the final solution, then (the Geshi version of) Codedoc just cannot be considered compatible with SQL.

**Comment by turnermm** [comment]
So be it.
